### ISSUE TITLE
Industrial Craft 2 Issues

### ISSUE THREAD

**Issue by Biggercheese** [TheBritishBrotherhood/ArdentCraft-The-Beginning#10]
Hi,

Absolutely loving the mod pack. I have noticed that IC2 blocks (cables, machines, etc...) will disappear randomly from the world. What is left is a shadow on the block they were placed on as though they were there. I'm unable to pass through said block even though it appears as though nothing is there. I did find that if I place a block such as cobblestone on that spot then break it, it acts like I broke the IC2 block that was there that had disappeared. This also happens for the cables. Once they disappear I can place a block and break it and then a cable will pop on the ground like I broke it. Any information would be greatly appreciated. 

Kind regards,
Biggercheese

**Comment by TheBritishBrotherhood** [comment]
Is this in single player or the server?

Is this after an update?

I need more information :)

**Comment by Biggercheese** [comment]
Ah, it was a server running on 1.12.00 ArdentCraft. Thanks for reaching out
to me. I just updated the server to 2.3 and have yet to try out IC2. This
pack is amazing by the way. I have a couple friends all playing on the
server with me and everyone is loving it.

**Comment by TheBritishBrotherhood** [comment]
Thats great to hear! :D 

We are working super hard to get it right!

Also the Recipe issues are due to craft tweaker, The dev has been noted and will hopefully fix this issue soon :) 

Regards, Curtis

**Comment by vincentmet** [comment]
is this still a bug? or did CurtisLee1994 fix this already?

**Comment by TheBritishBrotherhood** [comment]
Cant be fixed as yet due to crafttweaker

**Comment by vincentmet** [comment]
no, he says the are randomly disappearing from the world, not something about recipes

**Comment by Biggercheese** [comment]
Hi all,

I havn't tried messing with ic2 since the bugs. Also last I checked 3 weeks
ago if I broke any mekanism item outside of creative mode it crashed the
entire game.

unfortunately I had to take a break. I'll be looking out for future updates
to the pack with increased stability. You guys are doing awesome! Thank you!

**Comment by TheBritishBrotherhood** [comment]
Some IC2 isues fixed in version 2.7.00 :) 

Recipe issue will be fixed in 2.8.00
