### ISSUE TITLE
Can no longer pick up crops

### ISSUE THREAD

**Issue by wolpoff** [TheBritishBrotherhood/ArdentCraft-The-Beginning#100]
Version 3.1.00

When right clicking on crops, the item drops, but just sits there. Can't pick it up into my inventory.  Haven't tried throwing down what's in my inventory yet, but can try that later. Tried a bunch of different crops from vanilla to mystical agriculture.  All behave the same.

**Comment by TheBritishBrotherhood** [comment]
Fixed in next update :) this is due to realistic drops, Ill roll out an update later today :) 

Thanks again for the bug reports!

**Comment by TheBritishBrotherhood** [comment]
Fixed in 3.1.01
