### ISSUE TITLE
Can't Atomically Reconstruct Quartz into Prismarine

### ISSUE THREAD

**Issue by wolpoff** [TheBritishBrotherhood/ArdentCraft-The-Beginning#102]
Version 3.1.01

The Atomic Reconstructor from AA should turn Quartz into Prismarine.  This does not seem to be functioning.  It does still turn a single piece of redstone thrown on the ground into the proper item.  But it does not interact with quartz.  Maybe the Realistic mod interaction?  Or a recipe issue?  It does show up in JEI though.

**Comment by wolpoff** [comment]
It does work with an AA Precision Dropper sometimes though.

**Comment by TheBritishBrotherhood** [comment]
It works fine for me each time:)

**Comment by wolpoff** [comment]
Agreed!  Just figured out this morning that it's due to the power
requirements.  So the beam pulse happens whether or not there is enough
power to "Reconstruct" the quartz.  Redstone requires a lot less so it was
working every time.  But Quartz only worked when there was enough banked
power in the reconstructor.

Thanks for looking into this as well!



-- Ben
