### ISSUE TITLE
Suggestion - Better Questing Auto Reload

### ISSUE THREAD

**Issue by ghost** [TheBritishBrotherhood/ArdentCraft-The-Beginning#106]
Hey there, this is just a shameless plug for my mod [Better Questing Auto Reload](https://minecraft.curseforge.com/projects/better-questing-auto-reload) which I figured you guys might appreciate as I know this is a rather large Better Questing pack. It is successfully being used [Forever Stranded](https://minecraft.curseforge.com/projects/forever-stranded) another popular questing pack.

**Comment by TheBritishBrotherhood** [comment]
Seems interesting, Can you just confirm to me what this mod does, i had a quick read and i dont fully understand :)

**Comment by ghost** [comment]
Unlike HQM, Better Questing allows you to have more than one quest line in any given minecraft profile. It lets you have an entire different quest set in each world if you want, but a consequence of this is that your changes do not automatically get saved to the "default quest set", which is what gets loaded up every time a new world is started. What this quest does is automatically saves the quests you are working on and sets them as the default without needing to type the command /bq_admin default save. Likewise, an existing world is loaded up this default quest set will be automatically reloaded, which means users will never have to type /bq_admin default load. I hope this helps.

**Comment by TheBritishBrotherhood** [comment]
I dont understand this part as we have never used this command? 

Likewise, an existing world is loaded up this default quest set will be automatically reloaded, which means users will never have to type /bq_admin default load. I hope this helps.

**Comment by TheBritishBrotherhood** [comment]
Also just realised who you are, Jump in my discord when you can and drop me a message about your mod :)
