### ISSUE TITLE
Enhancement plus Bug?

### ISSUE THREAD

**Issue by abdullamu** [TheBritishBrotherhood/ArdentCraft-The-Beginning#11]
God day 
*first of all i would like to thank you for the amazing pack and i would love to see more quick updates to the quests and exchanging applied energistics with refind storage plus adding rftools quest line please since i cant proceed without these quests being in the game so i can learn them.

*i don't know if this is bug or intended until you add rftools quest line but there's no receipt for the machine frame.

*and as enhancement can you add hotbar mod because big pack need multi items ready at use 
and lootbags since there are load of new mobs and very difficult it would be fair to get something as rewards from killing them and this is nice mod that add that.

*and it would be nice to add good rewards for finishing entire quest line for example finishing TC quest line give you nice pickaxe or axe or shovel or all in one mattock instead of chance cube which most of the time is destruction cube  not sure if its good reward or you can give reward bag from the mod lootbag plus chance cube.

*last thing maybe change the veinminer setting to be on pressed instead of sneaking which caused me problems and confusion since i sneak mine when im on the edge of lava and caused chunk of stone to destroy and death.

**Comment by TheBritishBrotherhood** [comment]
It is the mods fault there is no recipe.

Im going to try and update IC2 today, And hopefully i have no issues doing so :)
