### ISSUE TITLE
[3.1.01] Magical wood not crafting

### ISSUE THREAD

**Issue by Deme1983** [TheBritishBrotherhood/ArdentCraft-The-Beginning#110]
i found a issue with the magical wood not crafting. when i click the magical wood in JEI to see what it needs, i can see it clear as day one bookshelf and one gold. but when i go to craft it nothing happens. it wont craft! is there some other way im supposed to get it or is this a bug?

**Comment by wolpoff** [comment]
Works for me in 3.1.01. What version are you using?  And do you have the experience needed to craft it as well?

**Comment by Deme1983** [comment]
im using 3.1.01 and i think i had the exp needed how much does it need ?

**Comment by Deme1983** [comment]
i have 23 levels and when i use the bookshelf with the one gold next to it in the crafting grid it wont craft

**Comment by Deme1983** [comment]
ok found the issue .... i was trying to craft it in the Refined storage and i had to take it out and use a regular crafting table
