### ISSUE TITLE
Possible recipe overlap or just really hard recipe

### ISSUE THREAD

**Issue by wolpoff** [TheBritishBrotherhood/ArdentCraft-The-Beginning#111]
Version 3.1.01

In order to make some of the later tier IC2 items, e.g. Crop-Matron, you need Advanced Circuits from Advanced Rocketry.  But in order to make those you need Silicon Wafers from a Cutting Machine.  But to get the Cutting Machine you need a libVulpes Machine Structure.  For that you need Iron Rods.  Most recipes for the compatible Iron Rods are overridden by other recipes, e.g. Iron Plate.

The only method I can find for making Iron Rods is to stamp them with the Immersive Engineering Multi-block Metal Press structure.  So, is it intended that you need to build out most of Immersive Engineering in order to build a number of Advanced Rocketry structures, so that you can build crop management in IC2?

Seems excessive with the early game Actually Additions Farmer and the Ender IO Harvesting Station?

But if it is intended. Coolio and I'll happily move on.  If it's not, and the Advanced Rocketry parts for the IC2 builds is perhaps recipe overlap or something... that's even cooler :)

**Comment by TheBritishBrotherhood** [comment]
Sounds like recipe overlap etc, Dig around more in the recipes im sure there will be an easier way... If not i like it.. its staying ;) haha

**Comment by wolpoff** [comment]
Been through it pretty thoroughly. Really don't see any other paths. But
I'll start working on those components. Havent used IC2 crop stuff before.
So I'll see if it is that much better than the others and worth doing
again.  Was planning on building advanced rocketry anyway at some point.
Just already at a point where I have enough automated resource generation,
so from a progression standpoint it is an incremental improvements for an
exponential effort.

For all that description though, keeping it as is is still a totally valid
choice. :)

**Comment by wolpoff** [comment]
Oh.. and now I just learned gotta build the Advanced Rocketry Crystallizer, and Precision Assembler as well... and a Mekanism crusher in order to get the silicon needed.  And the Advanced Rocketry stuff is more multibock machines.  I think at this point I would suggest that it's a pretty crazy build tree just to get the IC2 crop stuff.  Not that the difficulty might not be warranted for another part of the IC2 tiering, but crop management shouldn't be this late game in my opinion.
