### ISSUE TITLE
Flower Pouch Contents wiped when placed in ME System

### ISSUE THREAD

**Issue by Dewfire** [TheBritishBrotherhood/ArdentCraft-The-Beginning#114]
Titles says it all, on the server I placed my Flower Pouch accidentally in my ME system and when I took it back out all the flower contents were set to 0.

This was the Applied Energistics 2 system.

**Comment by TheBritishBrotherhood** [comment]
I have tagged as fixed, But theres nothing i can do about this bug, Speak to the mod dev about this :)
