### ISSUE TITLE
Crash on world load

### ISSUE THREAD

**Issue by Zubinator117** [TheBritishBrotherhood/ArdentCraft-The-Beginning#115]
Title basically. I load up the world, it crashes. It hasn't been created yet. I have about a few seconds before it crashes. log: http://pastebin.com/q3de00ch

Thanks

**Comment by vincentmet** [comment]
had this issues before, it was caused by ender io. Should fixed relatively easy. Dont know when curt will do.

**Comment by Zubinator117** [comment]
so, what should I do?
