### ISSUE TITLE
[Suggestion/Improvement] Foamfix 

### ISSUE THREAD

**Issue by accessdenied0** [TheBritishBrotherhood/ArdentCraft-The-Beginning#116]
Hello ArdentCraft-team,

I have as suggestion for your team to add [Asie's Foamfix](http://asie.pl/foamfix/) to your modpack to improve your Memory usage and performance. I discovered this mod in Skyfactory 3 and so far I have been used it in all of my own packs and modpacks I downloaded to improve their performance (Anarchy edition). 

If you use it or not is up to you guys but I'm very happy with it.

access_denied

**Comment by TheBritishBrotherhood** [comment]
Thank you for the great suggestion, Were actually allready one step ahead of you ;) 

Its in the next up due to release in the next few days :D 

Curtis

**Comment by accessdenied0** [comment]
@CurtisLee1994 cool, that is really neat!

Can you tell if any mod or Quest might get removed, so I can avoid them? or Do you plan to add 9x9 Crafting?

Can't tell if you already have locked into it, but I have a few suggestions of mods I like very much:
Project Red, Cyclic, Crafting Craft, Crafting Tweaks and Tiny Progressions.

I can't wait for the full version with expert recipes. So far I'm very happy with this mod-pack. Good Work and thank you for your work.
