### ISSUE TITLE
Abyssalcraft - Asorah's Dreaded Gateway Key Issue

### ISSUE THREAD

**Issue by Deme1983** [TheBritishBrotherhood/ArdentCraft-The-Beginning#119]
hello the main function of the key is the right click to make a portal to Abyssal wasteland and the Shift Rightclick is supposed to make the portal to the Dreadlands but it only makes the first portal. i will not make the new portal, the Abyssalcraft version we have is 1.9.3.10, and i don't know if its a bug with the mod or a config issue of the modpack if you know of the issue or a possible fix

**Comment by TheBritishBrotherhood** [comment]
Are you using each key in the following dimensions?

**Comment by Deme1983** [comment]
is it supposed to be used in the abyssal wasteland dimension ? it said in the book can be use anywhere

**Comment by Dewfire** [comment]
1st key is used in Overworld, all the others have to be used in the Previous Dimension that they would be crafted in.
