### ISSUE TITLE
Silex not dropping their uncooked meat

### ISSUE THREAD

**Issue by ghost** [TheBritishBrotherhood/ArdentCraft-The-Beginning#12]
ever since the Update with the removed lapis drop from silex, they wont drop their meat anymore.
this is a minor issue, but for people wanting a strider as mount/pet/whatever, this is a bit bad.

**Comment by TheBritishBrotherhood** [comment]
I will look into it thank you :)

**Comment by TheBritishBrotherhood** [comment]
We removed there drops in one of the updates, As we didnt want them to drop Lapis, Seems we cant have either or, So im afraid there drops are now not a thing :) 

Regards, Curtis
