### ISSUE TITLE
AE Wireless Booster Uncraftable/Ender Pearl Dust

### ISSUE THREAD

**Issue by Dewfire** [TheBritishBrotherhood/ArdentCraft-The-Beginning#120]
Ender pearl Dust is required to build the AE Wireless Booster.  however the only way to make Ender Pearl dust is with a small Pile of Ender Pearl Dust, and per JEI the only way to get a Small Pile of that is by breaking down a full pile of the dust...

**Comment by TheBritishBrotherhood** [comment]
Change to use enderpearl powder.

Will be fixed in the next update
