### ISSUE TITLE
Supremium Hoes question

### ISSUE THREAD

**Issue by Deme1983** [TheBritishBrotherhood/ArdentCraft-The-Beginning#122]
is it possible to allow Supremium hoes in the Ender IO Farming stations ? after crafting and gathering for so long it would be nice to actually use them.

**Comment by TheBritishBrotherhood** [comment]
Will look into this for the next update :)

**Comment by Teyson** [comment]
Just make a mattock out of paper (only paper) and put 5 reinforced upgrades on it. You then get an unbreakable tool to put in your farming stations

**Comment by Deme1983** [comment]
i didnt know the mattock worked int he Ender IO farming station ill take a look into it

**Comment by Teyson** [comment]
It does, and its fantastic as it works as both a hoe and an axe
