### ISSUE TITLE
Mek Jetpack Recipe Removed - Quest Un-completeable?

### ISSUE THREAD

**Issue by Trug42** [TheBritishBrotherhood/ArdentCraft-The-Beginning#124]
With the mekanism jetpack recipe being removed, this appears to break the Mekanism questline which requires crafting a jetpack. Is this intentional with a workaround, or just stuck until a new recipe is introduced in a future version? 

Thanks!

**Comment by TheBritishBrotherhood** [comment]
Thanks for the report :D Will be sorted by the next update
