### ISSUE TITLE
Builder set to Quarry(Replace with dirt) + Lycanite Geonach= impossible...?

### ISSUE THREAD

**Issue by kileroy** [TheBritishBrotherhood/ArdentCraft-The-Beginning#126]
To sum it quickly, this little son of a rocky mountain make it mostly impossible to let a quarry run for more then a minute. For whatever reason, when the quary run and break a ore (I guesse), the possibility to wake a Geonach is still there, problem is, they pop right next to the builder and "breaking" it.
Don't know if this does it with the 'clear' quarry, but still a problem, in my perceptive.
Hope it help a bit.

**Comment by TheBritishBrotherhood** [comment]
This is for sure a big issue, What quarry are you using? ExtraUtils? And what version of the modpack :)

**Comment by kileroy** [comment]
The Builder, like I said, with the shape card Quary for replacing the block with dirt (so not the 'clear' one). And juste updated to the lates, so 3.2.0.0 if I don't say silly thing for thee hour.
The ExtraUtils' one just crash the game for me sadly.

**Comment by TheBritishBrotherhood** [comment]
Okay, I iwll look into these issues thank you

**Comment by kileroy** [comment]
Not to burst a bubble here, and I know you work on the other pack, but I've just updated to v. 4 and test my quary in the RF dimension, and after a minute a Geonach pop-up, making the Builder 'break' on the floor again. 
Is there something I'm not doing right? =s

**Comment by TheBritishBrotherhood** [comment]
I cant fix this issue, Would have to speak to RF and Lycanites dev :)

**Comment by WareX-Provider** [comment]
Try to change these options in config/lycanitesmobs/lycanitesmobs-spawning.cfg:
B:"CROP Player Only"=false to B:"CROP Player Only"=true
B:"ROCK Player Only"=false to B:"ROCK Player Only"=true
B:"TREE Player Only"=false to B:"TREE Player Only"=true

**Comment by kileroy** [comment]
Yup, did the trick. Thanks a little bit late. Too bad It took that mush time for that answer. Now lets gets back to fix my nether that 3 OP wither got on a rampage and remake that red matter katar that drop in the lava cause of a special mob...
