### ISSUE TITLE
Osmium Ore is missing a mining level

### ISSUE THREAD

**Issue by Rakinare** [TheBritishBrotherhood/ArdentCraft-The-Beginning#13]
Osmium ore is missing a mining level, which means you can mine it with a wooden pickaxe. The problem with that is, that you can use it to craft an osmium pickaxe which has a mining level of diamond, so you are pretty much in midgame as soon as you find osmium.

A mining level has to be added to osmium ore.

**Comment by TheBritishBrotherhood** [comment]
Fixed in a upcoming update!

Thank you :)
