### ISSUE TITLE
Update 32.0.1 Old Quest Bookfiles?

### ISSUE THREAD

**Issue by GhostTwohand** [TheBritishBrotherhood/ArdentCraft-The-Beginning#130]
Update 32.0.0 added the new Quests, but with 32.0.1 the new added Quest are gone... It's like before the Questbook update.

Even after Redownloading the Pack the Questbook is pre-32.0.0

**Comment by TheBritishBrotherhood** [comment]
They were removed for the time being due to a an issue/spam.

Will be fixed for the next update
