### ISSUE TITLE
world not loading

### ISSUE THREAD

**Issue by hopey3182** [TheBritishBrotherhood/ArdentCraft-The-Beginning#14]
I just updated to the latest update today, and when I launched the pack and tried to launch my world, it just says "building terrain" and won't actually load the world. Not sure what the problem is. Any suggestions?

**Comment by TheBritishBrotherhood** [comment]
Hmm this seems to be a bug that keeps a appearing out of no were.

Are you able to succesfully boot into a new world?

Also please send me the Console log so i can see whats happening.

Thank you :)

**Comment by hopey3182** [comment]
I haven't tried creating a new world, but I just tried to launch the pack and it crashed. Here's the crash report. I noticed it said at the bottom something about me being out of memory but I've been using the pack and there hasn't been any problems? Not sure what to do lol.
[crash report.txt](https://github.com/CurtisLee1994/ArdentCraft-The-Beginning/files/587973/crash.report.txt)

**Comment by Psykofreq** [comment]
I had a similar issue. Could not load in, and it would also hang creating a new world.

**Comment by TheBritishBrotherhood** [comment]
Hopey, Try dedicate more ram to the pack.. Im not sure why the worlds are crashing either! 

CratTweaker seems to be causing the pack alot of issues! So hopefully there new update fixes this! If either of you can send me you console Log so i can send it to the dev! ive been unable to recreate this issue, but i know this issue is alive

Regards, Curtis

**Comment by MokahTGS** [comment]
Getting the same issue of the world (a new world) not loading getting stuck on "Loading Terrain"

Here's the console:  http://pastebin.com/TysJGqne

**Comment by MokahTGS** [comment]
More: https://dl.dropboxusercontent.com/u/9882100/Minecraft/ardent_latest.log

**Comment by TheBritishBrotherhood** [comment]
Try deleting the pack and re-installing, If the issue still persists. Let me know :) 

Regards, Curtis
