### ISSUE TITLE
Fireworks every minute after i started the world

### ISSUE THREAD

**Issue by SirSpart** [TheBritishBrotherhood/ArdentCraft-The-Beginning#148]
So i started my first world with this mod and every minute there is a firework, causing lag and annoyance for no reason. Initially i thought it is because of achievements, but after 10 minutes of unlocking no achievements, i am still getting fireworks every minute apprx. Is this a bug or an annoyance feature?

**Comment by webtyphoon** [comment]
Hi there,
its since yesterday evening around 11:00 PM (CET). I logged off after 30-40 firewords in a row. I don't think it have to do with the pack - Maybe a API connection to a mod or minecraft it self.

**Comment by Essk** [comment]
I fired up the pack first time this morning, fireworks every 20 seconds or so, even 2 hours in. Restart of the client did not stop it. It would be great if you could confirm if this is a bug or a feature :)
Thanks

**Comment by th3exodus** [comment]
I think this is an April Fools Day thing.  I just installed the pack and same thing guys.  If it is an April Fools thing than that is hilarious.

**Comment by ghost** [comment]
Stupid idea this fireworks :/

**Comment by webtyphoon** [comment]
maybe a april fool from a installed mod https://www.reddit.com/r/Minecraft/comments/62oybs/fireworks_randomly_triggering_suddenly_after/
