### ISSUE TITLE
Server Files 4.2.02

### ISSUE THREAD

**Issue by diraven** [TheBritishBrotherhood/ArdentCraft-The-Beginning#151]
[download](https://drive.google.com/file/d/0B0cU2kB7jB8ZZHhyUERtdjJHRGs/view?usp=sharing)

Remember to [handle eula.txt](https://www.akliz.net/manage/knowledgebase/44/How-to-Agree-to-the-EULA-on-a-Minecraft-Server.html) appropriately when server asks you to (see "Running on Your Computer" section).

How to create server files yourself:
https://github.com/TheBritishBrotherhood/ArdentCraft-The-Beginning/issues/139

**Confirmed working.**

**Comment by diraven** [comment]
@TheBritishBrotherhood it may be a good idea to either open wikis for external editing or just make a page there yourself explaining how to make server files for your modpack.

**Comment by ghost** [comment]
@TheBritishBrotherhood  hey dude, you modpack discord doesnt work, say that it expired. please check it.
