### ISSUE TITLE
Missing Recipe for Machine Base

### ISSUE THREAD

**Issue by Pierre-Dole** [TheBritishBrotherhood/ArdentCraft-The-Beginning#16]
As the title says there is no recipe for the RFTools Machine Base (https://ftbwiki.org/Machine_Base).

**Comment by TheBritishBrotherhood** [comment]
Theres an issue at the moment were Craft tweaker is removing recipes from showing in NEI.

If you find the recipe, The recipe should still work! 

If it doesnt please let me know and ill fix it today :) 

Regards, Curtis

**Comment by Pierre-Dole** [comment]
That was what I tryed first before I posted this. It doesn't work. :)

**Comment by TheBritishBrotherhood** [comment]
Recipe will be added to next update. Sorry for the long wait :)

**Comment by TheBritishBrotherhood** [comment]
Fixed in 2.5.00
