### ISSUE TITLE
Invisible Mobs

### ISSUE THREAD

**Issue by Enderboy360** [TheBritishBrotherhood/ArdentCraft-The-Beginning#163]
Sometimes I get a attacked randomly and I can't see the mob that is attacking me. . Than after I died, I ran back to my grave and I saw a devil chicken there. This has happened again few times later but it was a different Mob.

**Comment by Morpheus1101** [comment]
is this still an issue in v4.3 of the pack?

**Comment by Enderboy360** [comment]
I have no Idea. It is a random thing that happens. I will close this problem for now. If it happens again I will reopen it.
