### ISSUE TITLE
Expert mode

### ISSUE THREAD

**Issue by guinette** [TheBritishBrotherhood/ArdentCraft-The-Beginning#2]
hello

i search but i don't find the way to put the expert mode on ...

can you help me ?

thanks

**Comment by TheBritishBrotherhood** [comment]
Hey guinette, Expert mode isnt implemented just yet :) We are working on it, It should be added within the next few updates :) 

Regards, Curtis

**Comment by guinette** [comment]
Oh ok

Thanks for the answer ...

**Comment by Kuktar** [comment]
Is expert mode implemented yet? Thanks!@

**Comment by vincentmet** [comment]
no, we want to have a stable normal mod first, and then ill move on to continuing expert mode
