### ISSUE TITLE
Invisible mobs

### ISSUE THREAD

**Issue by JasonMcRay** [TheBritishBrotherhood/ArdentCraft-The-Beginning#21]
I don't know if it is a feature or a bug, but I have encountered Skeletons that are invisible and they just shoot me, I have no idea where they are shooting from, I even cannot see the arrows they shoot.

Not only skeletons, but I was mining and Geonach spawned. I saw him, so I turned away and ran. Turned back he was nowhere to be seen, but something was hitting me, I was unable to move (probably because I tried to move "into" the invisible Geonach. Got killed of course by him.

If it is a feature, it would make a bit more sense to these mobs becoming visible when they attack, otherwise they are unkillable, if you don't see what and where it is hitting you.

Using the latest Ardentcraft (2.4.01) with added Optifine, changed Mousetweak config and removed/disabled Good Old Pvp mod.

**Comment by TheBritishBrotherhood** [comment]
With you changing the config for the modpack i wouldnt be able to bug test, If you can recreate this in version 2.5.00 let me know.

Regards, Curtis
