### ISSUE TITLE
Philosopher's stone - Essence of Gatekeeper, really?

### ISSUE THREAD

**Issue by eslachance** [TheBritishBrotherhood/ArdentCraft-The-Beginning#22]
I get that the stone is... sorta infinite resources, but I imagined looking at the recipe and especially the order of things in the Quest "book" that it would still be... "relatively" early on. But from what I see on the internet, that Essence of Gatekeeper is basically something you get endgame, with fully upgraded top level armor and hours and hours of toiling in dimensions from AbyssalCraft

Are you *sure* you can't make that maybe a little less "completely out of reach"? Make it... oh I dunno, a 64k cell from AE2? Extreme crafting but no "go out and fight this boss that TPs you in the death dimention with nothing on you" thing...

**Comment by TheBritishBrotherhood** [comment]
This pack is meant to test your sanity, Project E is suppose to to hard as its over powered! We actually wanted to make it harder :) 

Sorry but it will be staying the way it is 

Regards, Curtis
