### ISSUE TITLE
Quest log

### ISSUE THREAD

**Issue by TheSphix** [TheBritishBrotherhood/ArdentCraft-The-Beginning#23]
Why is it so that if other palyers open the quest log on the Lan server mine gets opned too?

**Comment by Kuktar** [comment]
Were do you get the server files?

**Comment by TheSphix** [comment]
I using open to lan

**Comment by Kuktar** [comment]
Oh so you downloaded the modpack then run it and open it with others on your LAN. The reason all people have same quests is probably becuase they fall under your data in your %appdata% just a wild guess though but HQM saves it differently if it's running on a proper server.

**Comment by TheSphix** [comment]
No it is like if you and me play then you open your quest log mine gets opned too but if i open mine only mine get's opned

**Comment by TheBritishBrotherhood** [comment]
Because your playing over lan and not on a server :)

**Comment by TheSphix** [comment]
But where is the server files you we been talking about?

**Comment by Kuktar** [comment]
I would love server files also :p

**Comment by Kuktar** [comment]
the creator of the modpack has the server files on curse. here is the page and a link

https://minecraft.curseforge.com/projects/ardentcraft-the-beginning/files/2353061

you actualy have to scroll down to additional files and the server files are there.

I hope this helps you, it sure has me excited.

https://minecraft.curseforge.com/projects/ardentcraft-the-beginning/files/2353039#additional-files

Also i am more than happey to help if you have never set up a server before. its not super hard but it does take a little more effort than single player lan game. Let me know.

**Comment by TheSphix** [comment]
Thanks!
