### ISSUE TITLE
Ender IO Farming Station - Hoes

### ISSUE THREAD

**Issue by ecstace** [TheBritishBrotherhood/ArdentCraft-The-Beginning#24]
Version 2.500, private server
The Ender IO Farming Station will not accept any hoes.  I have tested all available hoes in the pack, none are valid for the machine.
Axes are accepted fine.

Cheers
ecstace

**Comment by ANTdentarg** [comment]
Confirmed, to revert this change all you need is the 2.4 config for ender IO "Minecraft/config/enderio/enderio.cfg". There's an entry for accepted hoes.

**Comment by CurtisLee1994** [comment]
Will be fixed in the next update, Thank you for the report :D

**Comment by vincentmet** [comment]
Unfortunatly i wont be able to fix this soon. I tried it myself, and i have the problem too(all the values for the hoes in the config are on true). I also tried to update it, but it cant load the world/create new ones, when i do so.

**Comment by Heyo13579** [comment]
To me this seems like a mod compatibility issue try removing the mods added in the last update and add them one by one and restarting the game each time you add another mod until the issue arrives this should help isolate the issue to a fixable range

**Comment by ANTdentarg** [comment]
not sure what caused this to happen between 2.4 and 2.5, but if you remove (place it elsewhere) enderio.cfg (place it elsewhere) it will generate a new one with the hoes list intact. that's what it should look like, just copy that section. "# Use this to specify items that can be hoes in the farming station.", the big "hoes" section with "# Each value of this category is an item that could be a hoe. You can add more values." is already fine.

**Comment by vincentmet** [comment]
oke, ill try this today

**Comment by TheBritishBrotherhood** [comment]
Fixed as of 2.7.00
