### ISSUE TITLE
Quests missing objectives/autocompleting with nether star icon

### ISSUE THREAD

**Issue by Mechalith** [TheBritishBrotherhood/ArdentCraft-The-Beginning#25]
Every time I start a world, about the 2nd or 3rd time I load the game, Better Questing will go nuts and spam a dozen quests or more than just complete themselves for no apparent reason. When I look at them, there will usually be an objective showing but no reward. Any idea WTF and/or how to fix it?

**Comment by TheBritishBrotherhood** [comment]
Try delete and reinstall the pack, If the issue persists, Please let me know :)

**Comment by vincentmet** [comment]
Because of no further comments, ill close this issue. Please make a new one is this is still a problem.
