### ISSUE TITLE
Universal cable crashed MC

### ISSUE THREAD

**Issue by newstartinsa** [TheBritishBrotherhood/ArdentCraft-The-Beginning#26]
I placed a basic universal cable in the wrong place. I was using a steel tinkers pickaxe to pick it back up, and it crashed minecraft twice. The server didn't go down. The other players on the server weren't effected.  I can destroy the cable in creative without crashing.

**Comment by TheBritishBrotherhood** [comment]
This is a bug with Mekanism, I would suggest reporting it to him, Its not something i can fix unless i remove the recipe for this item, Ive been told if you use the wrench you are able to pick it up fine :)

**Comment by Tntdruid** [comment]
just update to Mekanism-1.10.2-9.2.1.295

**Comment by vincentmet** [comment]
Ill do it in the next update ;)

**Comment by TheBritishBrotherhood** [comment]
Fixed as of 2.7.00
