### ISSUE TITLE
Ore spawn rates need to be fixed

### ISSUE THREAD

**Issue by Heyo13579** [TheBritishBrotherhood/ArdentCraft-The-Beginning#27]
Ive been playing the mod pack for about a week now and i've noticed that some of the ores that should be very easy to find are turnign out to be the rarest of them all ores such as aluminum and menecio are one in a million i set up a quarrry area of about 200x200 and dig to bed rock and only found a hand full of both. seeing how there are so many mods that add ores it seems that the spawn rates need to be tweaked a bit in order to keep the normal rarity of ores in check.

**Comment by vincentmet** [comment]
No, this is not intended, ill try to fix it in one of the next couple of updates! But for now a way to get more is the Magical Crops mod.

**Comment by TheBritishBrotherhood** [comment]
Magical crops is suppose to be rare. 

Aluminum isnt rare. Its named Bauxite :)
