### ISSUE TITLE
SoundFilter included with the 2.6 server mods.

### ISSUE THREAD

**Issue by Farinhir** [TheBritishBrotherhood/ArdentCraft-The-Beginning#28]
It seems SoundFilters (which turns out to be a client side mod if my google is correct) is included with the server pack. I was able to start the server by disabling it. I thought it would be nice for you to know it is there.

**Comment by vincentmetevelis** [comment]
Didnt realize that mod was still in there... Thanks for noticing/telling it :P

**Comment by vincentmet** [comment]
Didnt realize that mod was still in there... Thanks for noticing/telling it :P

**Comment by vincentmet** [comment]
Server Files are updated
