### ISSUE TITLE
Pack Not Loading

### ISSUE THREAD

**Issue by cheflethalplays** [TheBritishBrotherhood/ArdentCraft-The-Beginning#29]
I just downloaded and tried to play this pack, but it gets hung up near the end of loading. It gets stuck when "Completing Minecraft initialization" is 7/7, "Reloading-ModelManager" is at 50/70, and The 3rd bar gets stuck anywhere between 16000 or 18000/60840.

Is anyone else experiencing this?
![image](https://cloud.githubusercontent.com/assets/24621535/21286703/f1a1c81a-c428-11e6-9c25-3b5e0c787534.png)

**Comment by vincentmet** [comment]
How many RAM did you gave this pack, you should give it at least 6GB!

**Comment by Xelkyos** [comment]
I have the same problem, how do you give RAM to this pack ?

**Comment by vincentmet** [comment]
Go to the profile options of the pack ( https://gyazo.com/b3bfe11f2b9f74628f65f0a2e8da29e8 )
At "Memory Settings" uncheck the "Use System Setting" squire, and move the drawer ( https://gyazo.com/cd51c48d2492136a6a8d7d6a7bc68e0e )
