### ISSUE TITLE
Tinkers Table Quest Not Working

### ISSUE THREAD

**Issue by the1tc** [TheBritishBrotherhood/ArdentCraft-The-Beginning#3]
The quest for Tinkers' needs you to have the various tables, it says it's a retrieval quest. I had crafted them before I unlocked the quest, no credit. I picked them all up, still no credit. I thought maybe it was wood specific so I crafted the oak variants of everything (previously had spruce) still no credit. Am I doing something wrong or is the quest broken?

**Comment by TheBritishBrotherhood** [comment]
the1tc, We have all been experiencing different issues with the tinkers quest line, I will be working on it tomorrow and hopefully get an update out with a fix :) 

Thank you for playing <3

**Comment by TheBritishBrotherhood** [comment]
Should be fixed in the latest update :)
