### ISSUE TITLE
Where is Deep Resonance?

### ISSUE THREAD

**Issue by Jack029** [TheBritishBrotherhood/ArdentCraft-The-Beginning#31]
It seems Deep Resonance was removed. Is there a reason why? Why is it not mentioned in the Changelog?

**Comment by TheBritishBrotherhood** [comment]
It will have been a bug when updating the mod, Vincentmet will readd this to the next update, Thank you for letting us know :)

**Comment by TheBritishBrotherhood** [comment]
Fixed as of 2.7.00
