### ISSUE TITLE
Tinkers Tools won't damage mobs

### ISSUE THREAD

**Issue by Jack029** [TheBritishBrotherhood/ArdentCraft-The-Beginning#32]
After the update Tinkers tools, like Pick, Sword, etc., won't damage mobs. Even if I craft new ones. Regular weapons and other mods work well.

**Comment by vincentmet** [comment]
Ill look into this

**Comment by vincentmet** [comment]
I tested it, and i dont have the problem. It's most likely something on your side, il reccommend resrting the client, or reinstalling the pack
