### ISSUE TITLE
For those of you that don't have enough ram to play  (windows only)

### ISSUE THREAD

**Issue by Heyo13579** [TheBritishBrotherhood/ArdentCraft-The-Beginning#34]
Hey guys iv'e had a lot of my friends that i recommended this pack to just didn't have enough ram to dedicate to the pack in order to play it lag free so i'm writing this to help y'all be able to easily play this pack with little to no lag at all :D just follow the steps below to get a near lag free experience ill have steps listed for people with 6-12 gigs of ram on there laptop or PC:

*directions are for windows 10 users but its relativity the same for windows 7 and under its just slightly different*

If you have 6-7 gigs of ram the steps below will allow you to at least play the pack but with sever lag
if you have 8 gigs of ram they will allow you to play the pack comfortably with lag only within the first 20 minutes of starting the pack, at 9 gigs and above these steps aren't really needed but they with reduce any minor lag you may have. 

1. find a flash drive or external SSD that has a minimum of 4 gigs of space free.

2. plug it into your laptop or PC and make sure that it attaches to your computer firmly and is in an area where there is little chance if it being accidentally removed.

3. go into your file explorer and right click on the name of your USB device and go to properties. once there look for a tab titled readyboost and click on it.

4. once in the readyboost tab you will be given 3 options you will want to choose the option that says "use this device" or if you don't care about the USB device you can choose to dedicate it to this but in doing so the device will be reformatted and will only be usable for this purpose.

5. there should also be a section that ask you how much space you would like to use if you can max it out once done click "apply" or "ok".

***after you do this it is critical that you do not remove the usb device with out repeating the previous steps and then clicking do not us this device when you are finished other wise you can damage your computer.***

6. once you are done with this you can go ahead and open up the launcher for ardent craft once there in the bottom left corner click the edit profile button, after look at the bottom of the windo to a line titled jvm arguments and clear it and paste your respective line into the box from the options below:

*6-7 gigs of ram: -Xmx6G -Xms1G -XX:PermSize=256m -Dminecraft.applet.TargetDirectory="C:\Users\Admin\Documents\Curse\Minecraft\Instances\ArdentCraft The Beginning" -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -Duser.language=en -Duser.country=US

*8-9 gigs of ram: -Xmx6G -Xms2G -XX:PermSize=1G -Dminecraft.applet.TargetDirectory="C:\Users\Admin\Documents\Curse\Minecraft\Instances\ArdentCraft The Beginning" -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -Duser.language=en -Duser.country=US

*10+ gigs of ram: -Xmx6G -Xms4G -XX:PermSize=1G -       Dminecraft.applet.TargetDirectory="C:\Users\Admin\Documents\Curse\Minecraft\Instances\ArdentCraft The Beginning" -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -Duser.language=en -Duser.country=US

7. once you have pasted the line hit save and then start your Minecraft game!!! not it will take a while to load like normal but basically what you have dine is turned the USB device you have inputted into a temporary external ram drive giving your system more ram to work with there for speeding up your system

**Comment by vincentmet** [comment]
Thank you for writing this tutorial, I think ill put this on the curse page, so that other people will find this more easily!

**Comment by Heyo13579** [comment]
Your very welcome :D i love figuring out how to make stuff work ive even have my own server at one point that had about 50 plug ins on 4g of ram that was a toughy to figure out XD if you need any extra insight on an issue let me know id be happy to give you my take on it :)

p.s. heyo13579 is my in game name for just abotu every game there is aswell as my youtube user when this pack gits a bit further along in development im thinkg about doing a videothon on it maybe play for a few hours ^^

**Comment by vincentmet** [comment]
Oke, placed the tutorial as unlisted pastebin. I placed a link to it on the end of the cursepage, with a note, that you created it!

For now i close this thread, since it is no issue, if you still want to comment, please do so on the cursepage!
