### ISSUE TITLE
Crashing regularly since update

### ISSUE THREAD

**Issue by newstartinsa** [TheBritishBrotherhood/ArdentCraft-The-Beginning#36]
I've crashed at least 6 times today, Not server side, just client side. 3 times just running back to my house from a and 3 times coming back to overworld from the wasteland dimension. I tried to duplicate these on single player and couldn't. It is only a client side crash. Here are the crash reports. Any help would be appreciated.

I don't know what order the crashes happened but I know the last one was dimension hoping and the one before was just running. So I guess you can disregard the first 4, but I'm including then in case they have a helpful piece on info.

If this is the wrong please. I apologize in advance. 

[crash-2016-12-18_11.14.30-client.txt](https://github.com/CurtisLee1994/ArdentCraft-The-Beginning/files/659746/crash-2016-12-18_11.14.30-client.txt)
[crash-2016-12-18_11.24.17-client.txt](https://github.com/CurtisLee1994/ArdentCraft-The-Beginning/files/659747/crash-2016-12-18_11.24.17-client.txt)
[crash-2016-12-18_16.50.54-client.txt](https://github.com/CurtisLee1994/ArdentCraft-The-Beginning/files/659749/crash-2016-12-18_16.50.54-client.txt)
[crash-2016-12-18_17.01.51-client.txt](https://github.com/CurtisLee1994/ArdentCraft-The-Beginning/files/659748/crash-2016-12-18_17.01.51-client.txt)
[crash-2016-12-18_09.01.45-client.txt](https://github.com/CurtisLee1994/ArdentCraft-The-Beginning/files/659750/crash-2016-12-18_09.01.45-client.txt)
[crash-2016-12-18_10.43.03-client.txt](https://github.com/CurtisLee1994/ArdentCraft-The-Beginning/files/659751/crash-2016-12-18_10.43.03-client.txt)

**Comment by Heyo13579** [comment]
You haven't dedicated your ram properly you need to increase your Xms size to at least 2 gigs this should fix your issue

**Comment by newstartinsa** [comment]
So I'm guessing this is something I need to talk to my server hosting about?

**Comment by newstartinsa** [comment]
Contacted my server hosting these are the specs

-Xmx3584M -Xms3584M

**Comment by Heyo13579** [comment]
Set the specs to -Xmx6G -Xms2G if you have access to 8 g of ram on your server host if not then set it to a minimum of -Xmx4G -Xms2G. If you continue to experience crashes then increase your permgen size to 1G

**Comment by newstartinsa** [comment]
I can increase the server memory to 4096mb but I'm not sure an extra 500mb is going to fix it.

**Comment by Heyo13579** [comment]
To fix it it would have to be increased to a min of 8,000m and would have to be dedicated exactly as I've written it

**Comment by newstartinsa** [comment]
That's a crazy amount of memory for remote server hosting. We didn't have any issues until I updated the server files to 2.6.00. I'll revert the files back to 2.4.00.

**Comment by Heyo13579** [comment]
8,000m is only 8gigs of ram which is not a lot in terms of server hosting

**Comment by newstartinsa** [comment]
Your talking about $50-70 a month. There are a few MC hosting companies that won't go over 6gb. Maybe it's more than most MC users are used to needing. But it is a Beta pack. So it's either wait until it is better optimized or go with a different pack.

**Comment by Heyo13579** [comment]
Actually if you run your server off of of an SSN client it's only about $10-$20 depending on your provider. Mc server hosting site always way over price there stuff

**Comment by newstartinsa** [comment]
Well I googled SSN client and all I get is Social Security Number lol.

**Comment by Heyo13579** [comment]
Woops sorry I meant to type ssh

**Comment by Heyo13579** [comment]
Well it's really a ssl vpn server that you use a ssh client to run its very complicated but it makes owning a server a bit easier on the pocket

**Comment by newstartinsa** [comment]
I reset the server back to 2.4.01 and all of the crashes stopped. No memory changes needed. Maybe once I get a bit more experience I'll look into that. This is my first server, I want to get a bit of assisted help under my belt first. Thanks for the advice! and your time today!

**Comment by Heyo13579** [comment]
Any time :)

**Comment by vincentmet** [comment]
I hosted a server for over a year over here, an 8GB server is only $12 a months. They had a good service, and all that stuff. https://www.minespan.com/
Do with it what you want :P
