### ISSUE TITLE
Crash on loading

### ISSUE THREAD

**Issue by billy0222** [TheBritishBrotherhood/ArdentCraft-The-Beginning#37]
[Crash Report](http://pastebin.com/cK9kaks4)
I found that it's crashed by DecoCraft and after I disabled it, I can finally start the game.
P.S. It is the newest version on Curse.
Hope you can fix it.

**Comment by vincentmet** [comment]
did you change anything in a JSON files after downloading the pack? since i did not get the error...

**Comment by billy0222** [comment]
No, I start the game immediately after download the newest version on Curse

**Comment by vincentmet** [comment]
Try to reinstall it

**Comment by billy0222** [comment]
I did try that a couple times and even with giving it 8GB ram, it's still crash on the loading screen.

**Comment by vincentmet** [comment]
Since im not able to replicate the bug, nor find the JSON file of the error. I cant do anything to fix it...
