### ISSUE TITLE
AC 2.6.0 Loading Wrong Version of Better Questing

### ISSUE THREAD

**Issue by MokahTGS** [TheBritishBrotherhood/ArdentCraft-The-Beginning#38]
Your current version of AC (2.6.00) is linking to a recent legacy release of Better Questing which is incompatible with the 2.X.X.X versions of BQ and BQ Expansions.  Currently it is loading the 1.3.180 version and not the 2.3.179 version.  This mismatch is causing crashes.

**Comment by vincentmet** [comment]
I tried updating it, but it causes even more issues, for now, ill leave it on this version. Soon ill look for an solution!

**Comment by vincentmet** [comment]
This will be fixed i the next verion, but needs some time to un-corrupt the quests....

**Comment by TheBritishBrotherhood** [comment]
Fixed as of 2.7.00
