### ISSUE TITLE
(suggestion) wannabe evil?

### ISSUE THREAD

**Issue by Heyo13579** [TheBritishBrotherhood/ArdentCraft-The-Beginning#39]
Wanna make it a true hardcore pack you should add a darkness mod. so that at night you cant see 2 blocks in front of you with out a torch, but if you add this in you need to add in a mod that allows torches to be used in hand.

**Comment by Heyo13579** [comment]
oh and is there anyway commands to auto complete a quest i kinda jumped ahead in a few areas and it would take me for ever and be very redundant for me to redo them for the quest.

**Comment by vincentmet** [comment]
/bq_admin complete <questid>
or
/bq_admin edit (and the select the designer while in this edit mode, and then there should be an option for completing/uncompleting a quest)

**Comment by vincentmet** [comment]
and nah, we used it on another pack (TheDarkAge) and we didnt really like it... but thanks for suggesting it ;P
