### ISSUE TITLE
OreGen corrections

### ISSUE THREAD

**Issue by Mokeomehit** [TheBritishBrotherhood/ArdentCraft-The-Beginning#4]
Multiple mods generating the same ore type.
Tin, copper, nickle, lead, silver.
Mods: advancedrocketry, ic2, immersiveengineering, mekanism, neotech, forestry, TechReborn, libVulpes.

I disabled them in everything and let techreborn handle the generation. It tended to have the highest number of ores per vein.

Keep up the great work!

**Comment by Mokeomehit** [comment]
[changed configs.zip](https://github.com/CurtisLee1994/ArdentCraft-The-Beginning/files/530504/changed.configs.zip)

**Comment by TheBritishBrotherhood** [comment]
Thank you for the bug report, and thank you also for the changed configs! I will go over them, make sure everything works as should and if it works it will be in one of the upcoming updates :D <3
