### ISSUE TITLE
Crashing when trying to start up server

### ISSUE THREAD

**Issue by Dogzrkoolru** [TheBritishBrotherhood/ArdentCraft-The-Beginning#41]
[crash-2016-12-26_15.52.00-server.txt](https://github.com/CurtisLee1994/ArdentCraft-The-Beginning/files/673382/crash-2016-12-26_15.52.00-server.txt)
[crash-2016-12-26_15.34.50-server.txt](https://github.com/CurtisLee1994/ArdentCraft-The-Beginning/files/673383/crash-2016-12-26_15.34.50-server.txt)
[crash-2016-12-26_14.52.29-server.txt](https://github.com/CurtisLee1994/ArdentCraft-The-Beginning/files/673384/crash-2016-12-26_14.52.29-server.txt)
[crash-2016-11-18_14.51.00-server.txt](https://github.com/CurtisLee1994/ArdentCraft-The-Beginning/files/673385/crash-2016-11-18_14.51.00-server.txt)

**Comment by TheBritishBrotherhood** [comment]
Time: 12/26/16 3:52 PM
Description: Exception in server tick loop

java.lang.OutOfMemoryError: Java heap space

----------------------------------------------------

The server needs more memory dedicating to it! :) 

Regards, Curtis

**Comment by Dogzrkoolru** [comment]
and how would i do that i will prob look it up but thanks

**Comment by Al3366** [comment]
add more in your .bat file or .sh if you're on Linux
