### ISSUE TITLE
Crashing when killed the Gatekeeper

### ISSUE THREAD

**Issue by billy0222** [TheBritishBrotherhood/ArdentCraft-The-Beginning#42]
[crash report](http://pastebin.com/rEpPFjMj)
Whenever I killed the Gatekeeper, the explosion crash the game, and I cannot get the essence after re-open  the game.
It crashed my game three times...

**Comment by TheBritishBrotherhood** [comment]
Believe we have had this issue before, Could be to do with your system not keeping up, All i can suggest for now is cheating in the item you can't get :) 

I will try re create the issue and work on a fix in the meantime :)

**Comment by paucha171** [comment]
I had the same issue, I was running with 18 gigs of ram. I don't know if it's a lag issue or not, but I would say with that much oomph it might be something else...

**Comment by TheBritishBrotherhood** [comment]
Its happened to me also, Very strange issue im still trying to fix, ill wil do my best
