### ISSUE TITLE
Quest book still in edit mode

### ISSUE THREAD

**Issue by wolpoff** [TheBritishBrotherhood/ArdentCraft-The-Beginning#44]
Version 2.7.00
I know you have this lines up for the next update.  But I just thought it would be fun to have an easy close issue and polite reminder :)

**Comment by vincentmet** [comment]
I took it out of edit mode ingame, but forgot to do that in the config, Will be fixed in next update

**Comment by vincentmet** [comment]
Fixed in 2.7.01
