### ISSUE TITLE
Can sometimes turn in quest with previously crafted items

### ISSUE THREAD

**Issue by wolpoff** [TheBritishBrotherhood/ArdentCraft-The-Beginning#45]
Version 2.7.00

Looks like Crafting Task vs. Retrieval tasks...

I am trying to turn in the torches for the **It's Too Dark!** quest.  I had 16 torches crafted in a normal crafting table that I already had in my inventory.  But it wouldn't complete.  I had to craft 16 new torches in order for them to be detected and accepted.

However for the **Better Furnace** quest I just knocked a furnace off the wall and hit the detect button while it was in my inventory and it was accepted.

Not sure about the inconsistency or if the "breaking" of the furnace block allowed it to be detected whereas the torches and other items are never broken, just made, dropped, etc.  Actually, I didn't try placing and breaking the torches.  Just tried dropping them.  Can't break an iron pickaxe though.

Looked through the Better Questing forums, issues, wiki, etc. and couldn't find anything related to this.

Not sure this needs to be addressed, but while the quest lines are evolving, it can be a lot of work to go back and remake all these items.

**Comment by vincentmet** [comment]
For this i have to wait for an update from BetterQuesting. Or i have to change ALL crafting tasks to retrieval tasks, what will take up ages. That means it cant be fixed in the near future by myself
