### ISSUE TITLE
Text and reward issue with "Your going to need this...." quest

### ISSUE THREAD

**Issue by wolpoff** [TheBritishBrotherhood/ArdentCraft-The-Beginning#46]
Version 2.7.00

Title should read "You're" not "Your".

Also quest description should probably read: ... serve as **a temporary** 10% survival ...

Quest reward is odd.  Quest line already requires the player to create 16 torches two quests ago.  Not sure why a single torch as a reward is here.  Earlier on a single torch would be pretty nice.  Here is just seems, snarky, maybe?  As a player my preference might be for a small piece of armor, maybe some more decocraft, or a few pieces of food?  Otherwise, maybe just the chance cube?

If you want to let me know your quest line/reward philosophy, I'd be happy to look at them as I go through and see if I have constructive feedback, or I can keep some of my style to myself rather than bother you with suggestions that don't fit with the intended style.

Most of the quest lines look pretty linear, no rewards that you are required to keep in order to make progress in another line (which works for me!).  But it looks like the rewards are evolving and changing from the solely chance cube placeholders... not that they weren't fun ;-P

**Comment by vincentmet** [comment]
Title Updated, Desc updated, updated 1 torch to 64 torches.

The chance cubes ARE a replacement. Only some of the quests will remain the chancecubes. And if streamers/youtubers want to use it for donation/sub-stuff, they can spawn they in as OP

**Comment by vincentmet** [comment]
Fixed in 2.7.01
