### ISSUE TITLE
Quest text: Strainer Quest

### ISSUE THREAD

**Issue by wolpoff** [TheBritishBrotherhood/ArdentCraft-The-Beginning#47]
Version 2.7.00

For the Getting Started->Strainer quest there is a minor grammatical issue.

"Place the strainer base down in an at least 2 blocks deep pool of water" reads pretty awkwardly.  I would suggest either:
- "Place the strainer base down in an at least 2 block deep pool of water"
-"Place the strainer base down at least 2 blocks deep in a pool of water"

**Comment by vincentmet** [comment]
Fixed in 2.7.01
