### ISSUE TITLE
Quest text and order precedence: Baby power

### ISSUE THREAD

**Issue by wolpoff** [TheBritishBrotherhood/ArdentCraft-The-Beginning#53]
Version 2.7.00

For the quest Getting Started->Baby Power the text is challenging to read due to grammatical and spelling errors.  Also, it suggests that this is the first quest after building a "Better Furnace," but it's no longer the only generator in sequence after that quest. Note the ~~strikethrough~~ on the comma is hard to read.

Text suggestions:
Since you have some experience building furnaces, why not try **a** generator, but instead of ~~y~~**h**eat, ~~the~~**it** will generate RF ~~,~~ that can be used to power other machines.

**Comment by vincentmet** [comment]
Fixed in 2.7.01
