### ISSUE TITLE
Change deathsound

### ISSUE THREAD

**Issue by vincentmet** [TheBritishBrotherhood/ArdentCraft-The-Beginning#57]

**Comment by TheBritishBrotherhood** [comment]
Was allready changed.

**Comment by vincentmet** [comment]
it wasnt, it was lost in an rollback to 2.4.01

**Comment by TheBritishBrotherhood** [comment]
Just use the BWAAAH inception horn :)

**Comment by vincentmet** [comment]
Idk, i think ill spend some time looking for good possible deathsounds

**Comment by TheBritishBrotherhood** [comment]
Just make sure its copyright friendly

**Comment by vincentmet** [comment]
i wouldnt dare, you were the one who added the rickroll at first :P
