### ISSUE TITLE
Right Click Harvestablity

### ISSUE THREAD

**Issue by lbjodom** [TheBritishBrotherhood/ArdentCraft-The-Beginning#6]
Might want to disable the Right click harvest option on Pam's Harvest Craft due to the mod Mikes Dongles has the same option except mikes dongles crop dongles do not work if the option is enabled on pams as stated on Mikes Dongles curse page, "NOTE: As for version 0.1.3 and above, I recommend that if you using Pams HarvestCraft or EnderCore. Disable the Right Click functionality on both of those mods, and let Mike Dongle handle it. That way you get extra crops using the Crop Dongles."

**Comment by TheBritishBrotherhood** [comment]
Fixed in the next version. 

Thank you :)
