### ISSUE TITLE
Bauxite dust(s) orphaned

### ISSUE THREAD

**Issue by wolpoff** [TheBritishBrotherhood/ArdentCraft-The-Beginning#60]
Version 2.7.01

Looks like Bauxite crushes into Aluminum grit through almost all recipes.  But there looks to be one path through the TechReborn Bauxite Ore and the Immersive Engineering Hammer to get it.  Once you have it though, I'm not sure you can do anything with it other than break it into the Small Pile.

**Comment by vincentmet** [comment]
So, whats the problem here? (I read too much context, an no problem :P )

**Comment by wolpoff** [comment]
If you end up with Bauxite dust,  the only things you can do with it are break it into a small pile of bauxite dust, but you can't craft anything with the stuff.  At least from the recipes I see.  Doesn't even look like you can smelt it into an ingot of anything.  You just get dust.. that can't do anything but craft into itself.

**Comment by vincentmet** [comment]
Hmm, ill look into it

**Comment by vincentmet** [comment]
Hmm, ill look into it
