### ISSUE TITLE
Fishing rod doesn't fish

### ISSUE THREAD

**Issue by wolpoff** [TheBritishBrotherhood/ArdentCraft-The-Beginning#65]
Version 2.7.01

I am unable to get a vanilla fishing rod to work. I am casting it into water of various sizes.  I see the animation for the finishing bob moving around every now and then, but I never get the water splashing or fish swimming sprites.  I've let the bob sit out in the water for about 10 minutes with no catches or other sprites indicating it's working.  I did successfully use the same fishing rod in a previous version, I think before 2.7.00.

**Comment by vincentmet** [comment]
Ill look into this

**Comment by wolpoff** [comment]
Let me know if you think there are any experiments, or things I could do to
provide more info.  Happy to play around with it if it'll be helpful.



-- Ben

**Comment by vincentmet** [comment]
oke
