### ISSUE TITLE
Infinite mystical white flowers via plant harvest upgrade from Baubles Stuff

### ISSUE THREAD

**Issue by wolpoff** [TheBritishBrotherhood/ArdentCraft-The-Beginning#67]
Version 2.7.01

With a ring with the Baubles Stuff upgrade Plant Harvest Upgrade, it will infinitely harvest Mystical White Flowers from Botania.  It surprised me at first, and then didn't repeat, but I figured out that if there is a vine hanging down on top of the mystical flower, it causes it to infinitely harvest. Yay swamps I guess.

The most interesting part is if you have a different color mystical flower, you place it underneath the hanging vine, and then it kicks the non-white one out, replaces it with a white one, and then infinitely harvests white flowers.

Can probably capture a video or something if you need.  It's a weird one.  Had hundreds of the white mystical flowers flooding my inventory in seconds.  Not sure it's Ardentcraft's issue to fix.. but weird!

**Comment by vincentmet** [comment]
Haha, wut, if you would like to make a small video of it, that would be great

**Comment by wolpoff** [comment]
Ok. Please see crappy video: https://drive.google.com/file/d/0B0CmhRPuv37CN3ExRUk1MkR6TmM/view?usp=sharing

:)

**Comment by TheBritishBrotherhood** [comment]
Very strange bug, I would report this to botania & Baubles mod devs :D
