### ISSUE TITLE
Wierd trigger for big lagspikes

### ISSUE THREAD

**Issue by DrakeArron** [TheBritishBrotherhood/ArdentCraft-The-Beginning#68]
So, as long as I have ram done correctly this pack runs great for me. However every so often, say maybe every have half hour or so, I get a *huge* lagspike, sometimes to the point of having to close the game, and it almost always happens imediately after I click to harvest a crop- so far with I think canola and sugarcane. I don't really have a crahs report, as the only thing in the log related to it  is 
"[Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2546ms behind, skipping 50 tick(s)
[13:22:00] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 231533ms behind, skipping 4630 tick(s)
[13:23:07] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 67601ms behind, skipping 1352 tick(s)"

Any idea what could be causing this?
Thanks! -Drake

**Comment by Dewfire** [comment]
I randomly get large lag spikes as well, but I have not noticed any particular trigger for them, they've happened when just crafting, or walking around.  My game will go to 'Not Responding" for 15-30 seconds and then recover.

**Comment by DrakeArron** [comment]
Yeah, I've noticed lately it *can* happen at other times, though after harvesting something appears to be the most often cause.

**Comment by vincentmet** [comment]
I dont really know if i can fix this, since i cant replicate the problem...

**Comment by requnix** [comment]
I didn't get lag spikes the first time I played. The next day I got it every few seconds, so I restarted after allocating 12GB of RAM (the highest setting the Curse launcher allows). Then I didn't encounter it anymore.

I think it was Java garbage collecting, as my machine has 64GB RAM and 2 GTX1080's so there's no reason for frames to drop to 0 FPS with the graphics set to "FAST".
