### ISSUE TITLE
AbyssalCraft WorldGen Config

### ISSUE THREAD

**Issue by Dewfire** [TheBritishBrotherhood/ArdentCraft-The-Beginning#69]
Currently the WorldGen config for Abyssalcraft is set to False for all Biomes but the Coralium Swamps. The Darklands Biomes are required to even get started in the mod so without them you are stuck and locked out of progressing in several other mods since this one is a gate to them.  Most notably ProjectE.

**Comment by vincentmetevelis** [comment]
Thanks for reporting

**Comment by vincentmet** [comment]
Thanks for reporting

**Comment by DrakeArron** [comment]
Hope you don't mind my asking, is this simple enough that you could just replace "false" with "true" in the config? I'd like to get this particular fix sooner if I can, and if its that simple I think I could do it on my own.

**Comment by Dewfire** [comment]
Yes and any new area's explored will have a change to generate the Biomes.
