### ISSUE TITLE
Major quest bug

### ISSUE THREAD

**Issue by DrakeArron** [TheBritishBrotherhood/ArdentCraft-The-Beginning#70]
So, I've just noticed that sometimes when I load my game world, I will randomly complete quests that I in no right mind can see how- for example, I just logged into the world and I somehow completed the "wide guard" quest, despite not even completeing the tinkers smeltery quest yet, let alone have the ability to complete wide guard in the first place. It's possible other quests have been completed, but as they don't turn blue if I haven't unlocked the quest (yet in this bug do say under them "completed" if I mouse over it), it would take a while to find all of them.
This only ever happens imediately as I load the world, however I have no idea why. perhaps it has something to do with lag? Anyway, I figured I should report this imediately. If you like I can try and take a few screenshots, but I don't think they would give much more information.

**Comment by vincentmet** [comment]
Is it only at new world, only on loaded world? or both? And could you include the screenshots?

**Comment by DrakeArron** [comment]
Only when I load the world, so when I start the game, click on the singleplayer and then load world, it happens then. Not sure if it happens on a new game though, if it does it appears to happen randomly- could take a few tries if it does happen then. And sure I'll try to get screenshots.

**Comment by DrakeArron** [comment]
http://imgur.com/a/FAvUb Here, I have more if you need but they all essentially show the same thing.

**Comment by JpaqGaming** [comment]
i have the same issue.  only on world load so far.  has happened the last 2 worlds i made.   somehwere between 5-10 quests auto complete when i log in.   normally in the mechanism trees.    and im no where near having those complete.  also sometimes if has a "new quest" generic icon..and others its the one its suppose to be.   one of the mechanism pipes is one thats happened a few times.

**Comment by vincentmet** [comment]
Oke, i had this one once before. I fixed it, but i think it got lost... But Im redoing all the quests soon, so that will include this too

**Comment by Xray299** [comment]
I got this issue now, And it started after the smeltery quest was done like DrakeArron first picture shows
So I got images too 
http://imgur.com/a/xzAia

**Comment by CDArena** [comment]
This is still a thing. The first time I noticed something wrong, the Copper Grit quest (which I already completed and claimed) was marked as Unclaimed - now I am unable to claim it  - it is "stuck" as completed but not claimed. Later on (including just a few minutes ago), seemingly random quests are marked as completed each time I started the game. This includes "Slay the British Man" (the wither, which I haven't killed yet). And a bunch are completed that are simply titled "New Quest" and show a Nether star icon: my Food 'n stuff now has 4 of the advanced apple quests like this; and two other Bosses quests.

This bug kind of makes the game unplayable.

**Comment by Xray299** [comment]
Ye I know I have a few images in my last comment on that new quest issue where you can't complete it and get the reward so just gonna restart when this gets fixed

**Comment by NazT-DragN** [comment]
Same here, although it's happening both when I start a new world AND when I load my LP world. Most of the time it just flashes Complete: New Quest, and when I open BQM I get Nether Star Icons all over the place instead of the quests.

Note: This is a bug I'm finding with BQM in ANY of the packs I try to play that have it. I'm not sure why pack creators jumped so quick to replace HQM (as it never had issues like this) with a mod that is KNOWN to be this buggy.  All it does is piss off the community and make things miserable for everyone that's experiencing this.

**Comment by iHonor** [comment]
I'm having the same bug. Is there any fix for this yet? This bug makes me kind of want to quit playing this modpack.

Like mentioned by @Xray299 I also got this bug after completing the Smeltery quest

**Comment by TheBritishBrotherhood** [comment]
Better questing mod needs an update, but when we update the book gets demolished and ruined, we are working on a fix :) but we need time as the book took 3 months to get to the stage its at now

**Comment by Omniwrath** [comment]
Any update on this? Still getting this bug. Love the pack, but this really ruins the feel of progression. Can't claim rewards for any of the bugged quests.
