### ISSUE TITLE
Crashes on quitting to menu.

### ISSUE THREAD

**Issue by jonuman** [TheBritishBrotherhood/ArdentCraft-The-Beginning#71]
http://pastebin.com/TWEShVE0

**Comment by vincentmet** [comment]
Oke, First, you dont provide anything of the pack like the version etc.
Second, this look more like an incomplete serverlog, not a crashlog...

Sooo, I need MUCH more information

**Comment by TheBritishBrotherhood** [comment]
Its a 1.10 issue. happens in most heavypacks.

No possible fix.
