### ISSUE TITLE
titanium?

### ISSUE THREAD

**Issue by paucha171** [TheBritishBrotherhood/ArdentCraft-The-Beginning#72]
is there currently no way of obtaining titanium in this modpack?

**Comment by vincentmet** [comment]
It should be in the ground... However ill check it later this week

**Comment by paucha171** [comment]
It is possible I may have accidentally messed up my oregen so I will try creating a new wild and checking for it

**Comment by TheBritishBrotherhood** [comment]
RUTILE ORE is your main source of titanium, Please check recipes better :D
