### ISSUE TITLE
Ender IO Alloy Smelter glass/Quite Clear Glass conflict

### ISSUE THREAD

**Issue by wolpoff** [TheBritishBrotherhood/ArdentCraft-The-Beginning#75]
Version 2.7.01

The Ender IO Alloy Smelter should make Quite Clear Glass when smelting sand.  It makes normal glass.  Normal glass doesn't could for fusedglass in recipes.  Recipe for Quite Clear Glass does not show up in JEI either.

Edit: Actually none of the fusedGlass types seem to have valid recipes.  Enlightened, Dark, etc.

**Comment by vincentmet** [comment]
Did you put it on the alloy mode, instead of the furnace mode?

**Comment by wolpoff** [comment]
I thought so.  Will double check later today. :)



-- Ben

**Comment by Swanne101** [comment]
Can confirm that the Alloy Smelter doesn't make Quite Clear Glass.  Had to use the chisel to achieve it.

**Comment by wolpoff** [comment]
Yeah, in Alloy Only Mode it doesn't do anything with sand.

**Comment by TheBritishBrotherhood** [comment]
Will be looked at and hopefully fixed in the next update!! Thank you for the bug report :D
