### ISSUE TITLE
"industrialize it" quests

### ISSUE THREAD

**Issue by Swanne101** [TheBritishBrotherhood/ArdentCraft-The-Beginning#76]
Unable to complete Wrench or Coffee quests.  The wrench recipe makes the TechReborn version, which does not complete the quest.  Can't grind coffee with any of the Grinders or Macerators from any mod, even the one you jump up and down upon.  

Ardentcraft version 2.7.01

**Comment by wolpoff** [comment]
I think this duplicates one of the items in issue #43.  I believe @vincentmet has addressed this for the next release.

**Comment by Swanne101** [comment]
Oh goodness!  Sorry for the duplicate posting and thank for you good news on the fix.
