### ISSUE TITLE
End Dragon Achievement

### ISSUE THREAD

**Issue by Dewfire** [TheBritishBrotherhood/ArdentCraft-The-Beginning#79]
Minor bug only for those that like to complete their Achievements, but the "Cursed End Dragon" does not trigger the Minecraft Vanilla achievement for slaying the End Dragon.

**Comment by TheBritishBrotherhood** [comment]
Im not actually sure why this has occurred, the dragon is simply renamed.

But i will look into it thank you for the report :)

**Comment by vincentmet** [comment]
It's a probelm in draconic evolution, not our pack
