### ISSUE TITLE
Crash when killing a mob with DPS effects

### ISSUE THREAD

**Issue by requnix** [TheBritishBrotherhood/ArdentCraft-The-Beginning#82]
I crafted a Shuriken from Tinker's with Lead, Bone, Lava Crystal and Silver. When I used it to kill a Rabbit, my game crashed. The first hit created a flame particle effect, but didn't crash the client, but the second hit did.

I've attached 
[the crash log](https://github.com/CurtisLee1994/ArdentCraft-The-Beginning/files/724460/crash-2017-01-23_19.23.59-server.txt) in case I'm misreading it.

**Comment by requnix** [comment]
Verified that it is repeatable and not an isolated occurrence.

**Comment by TheBritishBrotherhood** [comment]
Thank you for the information requnix, This will be looked into! If you could attach your save file to make it easier to test that would be great!

**Comment by requnix** [comment]
You can download the save [here](https://dl.dropboxusercontent.com/u/39072532/ArdentCraft.zip). I hope it helps.

**Comment by TheBritishBrotherhood** [comment]
Thank you :D
