### ISSUE TITLE
Launching the pack, incredibly slow

### ISSUE THREAD

**Issue by Wolfsokim** [TheBritishBrotherhood/ArdentCraft-The-Beginning#83]
First I have windows 10 64 bit. 4GB have been allocated to running the game. It gets really slow on the ModelLoader: baking part of the completing minecraft initialization phase, if I click at all within the window it will crash and say that it ran out of memory, which I find hard to believe

**Comment by requnix** [comment]
For reference, I have Windows 10 64-bit as well, with 64GB of RAM and it loaded alright with the default ~5GB of RAM allocated, but I get lag spikes where the FPS drops to 0 for seconds at a time unless I set the RAM allocated to Java up to the max of 12GB.

**Comment by abdullamu** [comment]
this could be due decocraft it uses lot of memory try to turn it off and see . and update to most recent forge they did some speed improvement when loading mods

**Comment by wolpoff** [comment]
The modpack recommends 6GB of RAM allocated.  I found with any less it did not run well and startup often hung.  With 6+GB I have had no issues.  If you are using Curse, you do need to set the allocation within Curse setting or it will override.  I ended up settling on 10GB where it would run smoothly and not be bogged down when I did stuff in my browser on a second screen as well.

**Comment by TheBritishBrotherhood** [comment]
Any less then 6gb this pack is almost certain to fail on loading, We have had some reports of some mods causing high CPU usage and i will be doing some vigorous testing and possibly removing said mods! :)

**Comment by CDArena** [comment]
As noted, make sure you give it 6GB or more of memory. If you notice it "sticking" at the 0 percent loading screen, try tapping ESC twice.
