### ISSUE TITLE
Hitting Rare Mobs causes crashing

### ISSUE THREAD

**Issue by Swanne101** [TheBritishBrotherhood/ArdentCraft-The-Beginning#84]
Hitting any a rare spawn crashes the game.  Happens every time and everyone logged on gets kicked, even if they aren't in the fight.

**Comment by wolpoff** [comment]
Of note, I've never encountered this crash in a local game.  @Swanne101 this is on the server right?

**Comment by Swanne101** [comment]
Yes, this is on a server.
