### ISSUE TITLE
Decocraft

### ISSUE THREAD

**Issue by abdullamu** [TheBritishBrotherhood/ArdentCraft-The-Beginning#85]
hello
decocraft uses lot of ram and causes slow start up and 90% of times freeze or very slow at the end due to eating up all ram allocated which is the recommended by you 6 GB.
the mod is fun and all but not for this big pack its already tight adding another huge mod which eats up 30% is problem so i recommend to be removed.

**Comment by TheBritishBrotherhood** [comment]
Thank you for the suggestion and report abdullamu, This will most certainly be looked at thank you!

**Comment by vincentmet** [comment]
if you remove this @CurtisLee1994 you have to replace all the quest rewards manually, and you dont have my support for the quests anymore. This pack already requires a beefy computer, so removing decocraft wont do that much to it

**Comment by TheBritishBrotherhood** [comment]
It will fix a huge issue, Playing the pack only requires around 4gb to play, Loading the pack needs around 7gb, So the less it has to load the less stress it is on ram

**Comment by abdullamu** [comment]
Well it could be that some mods are useless but are causeing the pack to be unstable/heavy for example i have the freezing and heavy loading like the others until i removed couple of mods which was useless and not affecting the pack and now its much better to the point that i added 30+ more mods now with total of 170 mods and its running with quite fast loading time even with decocraft in the pack plus all the mods are up to date. So i managed to optimize the pack by removing something that was causing problem, thats what i think since the result was 170 modpack with good loading time and stable with no crash, so maybe the pack should be checked for mods that causes the heavy loading of the pack.
If the pack will update ill check my modified and the new one and compare them and see which is better and find out wheres the problem and report it. Otherwise ill close this thread.

**Comment by TheBritishBrotherhood** [comment]
@abdullamu sounds great :D
