### ISSUE TITLE
Invisible Mekanism Jetpack and Freerunners

### ISSUE THREAD

**Issue by snoop787** [TheBritishBrotherhood/ArdentCraft-The-Beginning#87]
Version 2.7.01, wearing regular or armored Jetpack or Freerunners from Mekanism does not display the actual armor on the character model. Standard Mekanism armor (steel, glowstone, lapis, etc.) does appear on the model, and other modded armor displays as well. Didn't find any settings in the Mekanism config covering this.

Features of the jetpack and freerunners are still applied (negated fall damage, flight, armor points, etc.), but dangit I want to look cool. :P

"Paper doll" preview in Inventory:
![ardentcraft mekanism no armor 1](https://cloud.githubusercontent.com/assets/9879246/22275390/45197a82-e261-11e6-9bf7-e0083e1b6b67.png)

F5 view of same model:
![ardentcraft mekanism no armor 2](https://cloud.githubusercontent.com/assets/9879246/22275391/451e3aea-e261-11e6-8f13-6f04d3c508bb.png)

**Comment by TheBritishBrotherhood** [comment]
Thank you for the report Snoop, Ill take alook into it and try fix it for the next update, Could possibly just need to update the mod :P 

We are a little behind on updates, but regular updates should be starting again fro next week :D

**Comment by vincentmet** [comment]
This is a mod bug not one from the pack, unless the author fixes it, it cant be fixed
