### ISSUE TITLE
Recipe Changes not what they are meant to be

### ISSUE THREAD

**Issue by Deme1983** [TheBritishBrotherhood/ArdentCraft-The-Beginning#88]
hello me and a fiend play this pack together and for some reason there area alot of recipes not working JEI is showing stuff and when we try to build it it wont build

such as Stone Pickaxe [wont craft], Pickappa Pickaxe [wrong recipe], Storage Core [wont craft] and i'm sure there are a few others we haven't found yet. so why does it show one recipe for some things like the pickappa pick and be something completely different ? now we seen TheOnlyBently playthru of this pack and the recipes they have are still working but some are just not working at all. any ideas why ?

**Comment by TheBritishBrotherhood** [comment]
Stone pickaxe does work, Check the recipe ;) Pickappa again does work check the recipe ;) But yeah the rest are a bug thats been holding the pack back for a while, There will be an update soon with the recipe fix:D 

Regards, Curtis
