### ISSUE TITLE
Mod Suggestions

### ISSUE THREAD

**Issue by Dewfire** [TheBritishBrotherhood/ArdentCraft-The-Beginning#89]
I know this pack is already pretty large but there is one Mod I'd like to suggest to add in.

- [PSI](https://mods.curse.com/mc-mods/minecraft/241665-psi)

**Comment by TheBritishBrotherhood** [comment]
We have had this suggested many times! I will sure look into adding it as i will be removing ALOT of mods:)

**Comment by TheBritishBrotherhood** [comment]
PSI has been added to the next update
