### ISSUE TITLE
Mekanism Issues

### ISSUE THREAD

**Issue by Biggercheese** [TheBritishBrotherhood/ArdentCraft-The-Beginning#9]
Hi, I am absolutely loving the mod pack. I am currently experiencing issues with Mekanism. Please let me know if these are bugs or if maybe I'm not progressing correctly.

1. When trying to connect universal cable to the wind turbine on the power port at the base of the turbine it doesn't connect. It does however connect to a different side.
2. I'm unable pull power from power generation sources using universal cables. It doesn't seem like they are working.
3. No matter how many times I have tried I'm unable to get power in to an energy cube. I've tried universal cables, IC2 cables (insulated and non), NeoTech cables.

Greatly looking forward to hearing back from you.

Kind regards,
Biggercheese

**Comment by TheBritishBrotherhood** [comment]
This seems like a mod issue.

I would suggest reporting this to the Mekanism Mod Developer :) 

I however will forward this message to him :) 

Thanks you.

**Comment by Biggercheese** [comment]
Awesome thank you for the reply!

**Comment by Pierre-Dole** [comment]
I also found a mechanism bug. Game crashs if I break (with pickaxe or hand) an Universal Cable.

**Comment by Biggercheese** [comment]
So I updated our server to the most recent version. Thanks for all the
awesome work! One thing I noticed though is if I try to use a configurator
on Mekanism pipes or machines now it crashes Minecraft. Just wanted to let
you know.

**Comment by Tntdruid** [comment]
Update to Mekanism-1.10.2-9.2.1.295 fix that

**Comment by TheBritishBrotherhood** [comment]
Fixed as of 2.7.00
