### ISSUE TITLE
Cobaltite unusable?

### ISSUE THREAD

**Issue by wolpoff** [TheBritishBrotherhood/ArdentCraft-The-Beginning#90]
Version 2.7.01

Cobaltite Ore from Magneticraft can be turned into a cobalt ingot, but that ingot isn't compatible with any recipes to make anything that I can find.  May be orphaned due to mod conflicts or recipe overlap.

**Comment by nwoodthorpe-test1** [comment]
❤️ 💚 💙 💛 💜![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f5a4.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f499.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f494.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f491.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f468-2764-1f468.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f491.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f469-2764-1f469.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f49d.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f49a.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/2764.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f49f.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f60d.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f63b.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f493.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f497.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/2665.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/2763.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f618.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f49c.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f49e.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f496.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f495.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f49b.png?v7 "Logo Title Text 1")Seen by Nathaniel Woodthorpe at 00:05

**Comment by TheBritishBrotherhood** [comment]
Thank you for all the bug reports Wolpoff :D I will look into it thank you!
