### ISSUE TITLE
Slime Floating Isles

### ISSUE THREAD

**Issue by Deme1983** [TheBritishBrotherhood/ArdentCraft-The-Beginning#91]
hello again i was wondering why the Slime isles from Tinkers' Construct were disabled in the config ? was it because of possible lag ? because there are a few things that is used with the different slimes in Tinkers' that needs them.

**Comment by TheBritishBrotherhood** [comment]
They were removed one day when i was playing i thought to myself ''TOO DAMN EASY'' so i removed them and made recipes for other slimes that cant be found elsewere :D
