### ISSUE TITLE
Version 3.0.0 - Ender IO > Farming Station > Hoes - Not recognizing any

### ISSUE THREAD

**Issue by GitJiggyWit** [TheBritishBrotherhood/ArdentCraft-The-Beginning#93]
After update, none of the hoes are recognized as compatible with the Farming Station.

Tested with basic Wooden, Iron, Diamond Hoes.

Fixed by coping EnderIO > EnderIO.cfg sections from prior version of ArdentCraft.
Version 3.0.0 had this section in the CFG file blank.

Additional Notes:
In-Game > Mod Options > Ender IO > Config > Farm Settings > hoes > Everything defaulted flagged as "True" for all of the hoes, but does not appear to help.

Additional Notes:
Have only tested vanilla and Mystical Agriculture hoes after updating CFG file.

For version 3.0.0 and prior:
Mystical Agriculture Hoes are not valid (compatible) hoes for Farming Station.  Not sure if this is a bug, because there are mentions in EnderIO that it is not defaulted on.
Added:
mysticalagriculture:inferium_hoe
mysticalagriculture:prudentium_hoe
mysticalagriculture:intermedium_hoe
mysticalagriculture:superium_hoe
mysticalagriculture:supremium_hoe

**Comment by TheBritishBrotherhood** [comment]
Thank you for this extensive bug report, Would love to have you as a part of the team! 

If you want to help out more with this modpack please feel free to jump in my discord and PM me :D 

Regards, Curtis

**Comment by vincentmet** [comment]
curt, YOU SON OF A BITCH, you deleted my new config of 2.7.00 didnt you? I already fixed it there
