### ISSUE TITLE
Cannot make Industrial Craft 2 coffee

### ISSUE THREAD

**Issue by wolpoff** [TheBritishBrotherhood/ArdentCraft-The-Beginning#94]
Version 3.0.0

Thanks for the IC2 recipes! Unfortunately, for the quest line you need to make coffee, but I don't see any way of making IC2 coffee.  It's not compatible with the AA coffee and with no crops to crossbreed, you can't make IC2 coffee beans.

**Comment by TheBritishBrotherhood** [comment]
Thank you again for more bug reports wolpoff! Doing such a great deed for me :D 

I will get a recipe added for the next update, Unless you can think of a recipe then please feel free to suggest one :D

**Comment by wolpoff** [comment]
I'd be tempted just to overlap the dictionary to allow AA coffee to be
used.  That way you can leave out the crops and crossbreeding. :)



-- Ben
