### ISSUE TITLE
Looking for a recipe maker for expert mode!!!! PLEASE READ

### ISSUE THREAD

**Issue by TheBritishBrotherhood** [TheBritishBrotherhood/ArdentCraft-The-Beginning#95]
So you all want expert mode.

Been a one man team Making the pack along with doing expert recipe mode is too much of a task.

So i am looking for ONE person who has GREAT recipe making skills!

Expert mode for this pack will NOT be an easy task as i want to change alot of recipes.

You need to know how to import mods into craft_tweaker
Make recipes work well together will other mods
Make it hard but not tedious and also fun

This is a serious role so please read the next few lines.

If you are interested in becoming my expert recipe mode creator then you have to be a good listener, I have tried many times to work with people but they find it hard to listen to what i want for this pack.

You need to know mods and know how most of them work! If you have no mod knowledge please dont apply.

So instead of rambling here's what you need to do

Below this, comment with the following:

Modpack experience (months) = 
Recipe Experience (months) = 
Have you made your own modpack with recipe changes? (name of pack - yes/no) =
Do you work well as a team? (yes/no) = 
Are you willing to be tested? (yes/no) =
Do you have any mod development experience? (yes/no) =
Are you able to come up with fun and interesting recipe ideas? (yes/no) =
Additional information about yourself (tell me about yourself) = 
Anything else you want to say? =
Can you keep secrets? (yes/no) =

Feel free to answer with more then just a simple yes or no.

If you are successful i will call your name in the comments so please be sure to check back often :) 

Good luck :D <3

P.S, Sorry for the weirdness of this post

**Comment by KewaiiGamer** [comment]
Modpack experience (months) = at least 36
Recipe Experience (months) = at least 12
Have you made your own modpack with recipe changes? (name of pack - yes/no) = yes (It's private tho)
Do you work well as a team? (yes/no) = yes
Are you willing to be tested? (yes/no) = yes
Do you have any mod development experience? (yes/no) = yes (and you know that ;))
Are you able to come up with fun and interesting recipe ideas? (yes/no) = yes
Additional information about yourself (tell me about yourself) = I love to learn new stuff!!
Anything else you want to say? = Don't you dare deny this application!!!
Can you keep secrets? (yes/no) = yes

**Comment by vincentmet** [comment]
> If you are interested in becoming my expert recipe mode creator then you have to be a good listener, I have tried many times to work with people but they find it hard to listen to what i want for this pack. 
You are demanding those things, not let the maker choose. 

> Been a one man team Making the pack along with doing expert recipe mode is too much of a task.
2 person team...
