### ISSUE TITLE
Can't retrieve IC2 machines once placed

### ISSUE THREAD

**Issue by wolpoff** [TheBritishBrotherhood/ArdentCraft-The-Beginning#96]
Version 3.0.0

Breaking an IC2 machine with a pickaxe retrieves a Basic Machine Casing.  Breaking them with the IC2 wrench returns nothing.  I think it's pretty straightforward, but let me know if I can collect any more useful debug info.

**Comment by GitJiggyWit** [comment]
You should right-click with the IC2 Wrench on the machine.  If it just rotates it, right-click it again with the IC2 Wrench.

**Comment by wolpoff** [comment]
Tried that, they just disappear.



-- Ben

**Comment by TheBritishBrotherhood** [comment]
Seems like a bug with IC2, Ill keep an eye out for an update, But i would also report this to the IC2 devs :)

**Comment by wolpoff** [comment]
@CurtisLee1994 Any suggestions on additional info to add?  I don't see any reports on the I2C issues site that look related, and since it seems like a pretty fundamental bug, I'm guessing it's from some mod interaction.  Any  way for me to pull a useful log or something that might be helpful to them?  Thanks!

**Comment by TheBritishBrotherhood** [comment]
We have just tested this and we are able to pick up machines

**Comment by wolpoff** [comment]
I'll play around with it more tonight and see if I'm still experiencing the
issue.



-- Ben

**Comment by TheBritishBrotherhood** [comment]
No problem :) We used a wrench and seemed to work fine :)

**Comment by wolpoff** [comment]
Yep. Works for me now. Donno if I'm doing something different with the IC2 wrench or something else changed. But it's all good!  Thanks for the fast replies!

**Comment by wolpoff** [comment]
Actually, I think I reproduced it.  Shift-right-click with the IC2 wrench seems to dissapear the machine.  I'll take a look at the IC2 website when I can.  @CurtisLee1994, any chance you could give that a try and see if you have the same issue?
