### ISSUE TITLE
Having issues with a server with spawn rates

### ISSUE THREAD

**Issue by Deme1983** [TheBritishBrotherhood/ArdentCraft-The-Beginning#97]
hello again me and my friends with our private server noticed that there are a crap ton of mobs spawning at least 100 blocks away that seems to be slowing the server for some reason do you know of what mod / config that would be doing this or why the Mob Capper config isn't being read to cap the amount and or working at all

**Comment by TheBritishBrotherhood** [comment]
What version of the pack?
What mobs are spawning?
i need more info :)

**Comment by Deme1983** [comment]
version 3.0.00 (newest) and we had turned off lycanites and turned down everything else but something is forcing mobs (vanilla, creepers, zombies, and a crap ton of skeletons) to spawn and at least 100 blocks away but none near us and all underground we cant seem to figure out what is forcing mobs to spawn so far from the players at a alarming rate we even turned it peaceful for a second to see if things will be fine then and as soon as we turned it back to normal with a lot of spawn with in moments

**Comment by Tkdmaster** [comment]
Hey, the version we are using is 3.0.00 (latest curse release) and have disabled Lycanites in its config. I have subsequently tried numerous configurations with MobCapper, NoMobSpawningOntrees, RoughMobs, and Zombie Awareness with no success in reducing mob spawn numbers or distance.

With Lycanites disabled, the mobs spawning are vanilla mobs with Infernalmobs armor sometimes. Even after turning the server to peaceful, running entity kill commands to clear everything in the vicinity, and then turning it back to normal, the entity count skyrockets by ~40-80, almost all underground and well over 80+ blocks away, with very few hostile mobs spawning in closer.

**Comment by TheBritishBrotherhood** [comment]
from 2.6.00 to 3.0.00 nomob behaviour or mobs were changed, Not sure why there would be a mob issue now :/ 

This is differently a bug, Is it just server side or client aswell?

**Comment by Tkdmaster** [comment]
We haven't tested to see if it happens in a single-player world yet. An example for you though:

In NoMobSpawningOntrees config, I set the max monsters to 1, it has 0 effect on the server. I toggled peaceful on and off, and within ~10 seconds, the entity list went from ~90, to 40, and straight back up to 90, despite the hard cap limit I set.

In mobcapper, I have this as well:

    I:maxnumber=1
    I:range=128

and it seems to make no difference, as mobs still spawn in large clusters and near eachother.

**Comment by TheBritishBrotherhood** [comment]
I believe we removed the mob capper mod... 

Seems like a mod is causing random spawns of mobs, I would firstly test this in a client only world and see if the issue still persists

**Comment by Tkdmaster** [comment]
Well, since you mentioend that, I took a second look through the mods, and it would seem that RoughMobs is the only mod I lsited above that is actually in there, and the others are appearently just leftover config files...guess that would explain that part then!

As a small request then, please cleanup the configs a bit...? This has made things terribly confusing :)

That said, original problem still seems to persist, but I will solve it by adding in one or more of the above mods to my server to alleviate the problem.

**Comment by TheBritishBrotherhood** [comment]
Yeah i will get around to it one day, I have left them in for now incase i read said mods :) 

Tkdmaster, If you wanted to become a full tester for the pack join our discord and hit me with a PM sometime :)
