### ISSUE TITLE
EXPERT MODE - Is now in the works!

### ISSUE THREAD

**Issue by TheBritishBrotherhood** [TheBritishBrotherhood/ArdentCraft-The-Beginning#98]
Get excited ;) 

If you have any suggestions for expert mode leave them below <3

**Comment by Scionoftruth** [comment]
Definitely make sure you make use of Rice Crafting Table.
https://minecraft.curseforge.com/projects/rice-crafting-table

**Comment by TheBritishBrotherhood** [comment]
Rice crafting table was made for this modpack ;)
